// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kademlia.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	SenderID             string   `protobuf:"bytes,1,opt,name=senderID,proto3" json:"senderID,omitempty"`
	SenderAddress        string   `protobuf:"bytes,2,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	RecieverID           string   `protobuf:"bytes,4,opt,name=recieverID,proto3" json:"recieverID,omitempty"`
	RecieverAddress      string   `protobuf:"bytes,5,opt,name=recieverAddress,proto3" json:"recieverAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_79477522ae6a503a, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *Message) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetRecieverID() string {
	if m != nil {
		return m.RecieverID
	}
	return ""
}

func (m *Message) GetRecieverAddress() string {
	if m != nil {
		return m.RecieverAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "protobuf.message")
}

func init() { proto.RegisterFile("kademlia.proto", fileDescriptor_79477522ae6a503a) }

var fileDescriptor_79477522ae6a503a = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4e, 0x4c, 0x49,
	0xcd, 0xcd, 0xc9, 0x4c, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5,
	0x69, 0x4a, 0x2b, 0x19, 0xb9, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0xa4, 0xb8,
	0x38, 0x8a, 0x53, 0xf3, 0x52, 0x52, 0x8b, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0xe0, 0x7c, 0x21, 0x15, 0x2e, 0x5e, 0x08, 0xdb, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x58, 0x82,
	0x09, 0xac, 0x00, 0x55, 0x50, 0x48, 0x88, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x19, 0x2c,
	0x09, 0x66, 0x0b, 0xc9, 0x71, 0x71, 0x15, 0xa5, 0x26, 0x67, 0xa6, 0x96, 0x81, 0xcd, 0x65, 0x01,
	0xcb, 0x20, 0x89, 0x08, 0x69, 0x70, 0xf1, 0xc3, 0x78, 0x30, 0xb3, 0x59, 0xc1, 0x8a, 0xd0, 0x85,
	0x93, 0xd8, 0xc0, 0xae, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x4f, 0x53, 0x2f, 0xce,
	0x00, 0x00, 0x00,
}
